### ISSUE TITLE
Lost connection

### ISSUE THREAD

**Issue by 369Martin369** [Xinyuan-LilyGO/T-Display-S3#150]
I have a board, where a program is keeping the Serial Link 100% busy and now it does not respond to new program uploads.
Even with Flash Download Tool I get error...

test offset :  0 0x0
case ok

Uploading stub...
Running stub...
Stub running...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "download_process.py", line 678, in run
  File "espDownloader.py", line 601, in flash_download_test
  File "espDownloader.py", line 781, in flash_download_func
  File "espDownloader.py", line 697, in esp_stub_and_set_baud
  File "esptool\loader.py", line 916, in run_stub
  File "esptool\targets\esp32s3.py", line 232, in __init__
  File "esptool\targets\esp32s3.py", line 165, in uses_usb_otg
  File "esptool\loader.py", line 689, in read_reg
  File "esptool\loader.py", line 375, in command
  File "esptool\loader.py", line 307, in read
  File "esptool\loader.py", line 1415, in slip_reader
esptool.util.FatalError: Serial data stream stopped: Possible serial noise or corruption.

Any Idea how I can stop the serial noise and that the bootloader accepts commands???
Thx for any hint.

**Comment by 369Martin369** [comment]
found solution....Just hold down boot during reset, and board will respond with "waiting for download" instead of executing the program :-) Stupid me.....
